# -*- coding: utf-8 -*-
import os
import logging
import glob
import pyvista as pv

try:
    import psutil
    PSUTIL_AVAILABLE = True
except ImportError:
    PSUTIL_AVAILABLE = False


def get_memory_usage_mb():
    """Get current process memory usage in MB."""
    if PSUTIL_AVAILABLE:
        process = psutil.Process(os.getpid())
        return process.memory_info().rss / 1024 / 1024
    return 0.0  # Fallback if psutil not available


def load_from_vtk_files(sim_path: str, logger):
    """
    Load results from pre-generated foamToVTK files (memory-efficient).
    These files are generated by Inductiva during simulation.
    
    Returns:
        tuple: (internal_mesh, surfaces_mesh) or None if VTK files not found
    """
    vtk_dir = os.path.join(sim_path, "VTK")
    
    if not os.path.exists(vtk_dir):
        logger.info(f"    * VTK directory not found: {vtk_dir}")
        return None
    
    logger.info(f"    * VTK directory found: {vtk_dir}")
    logger.info(f"    * VTK contents: {os.listdir(vtk_dir)[:20]}")
    
    # Find the latest timestep VTK files
    # foamToVTK generates: <case>_<timestep>/<case>_<timestep>_internal.vtk
    # and surface files in subdirectories
    
    # Look for internal mesh files
    internal_files = glob.glob(os.path.join(vtk_dir, "**/*_internal.vtk"), recursive=True)
    if not internal_files:
        internal_files = glob.glob(os.path.join(vtk_dir, "**/internal.vtk"), recursive=True)
    if not internal_files:
        # Also check for .vtu files (unstructured grid)
        internal_files = glob.glob(os.path.join(vtk_dir, "**/*.vtu"), recursive=True)
    
    logger.info(f"    * Found {len(internal_files)} internal VTK files")
    
    if not internal_files:
        logger.warning(f"    * No internal VTK files found in {vtk_dir}")
        return None
    
    # Use the latest timestep (sort by name, last should be latest)
    internal_files.sort()
    internal_file = internal_files[-1]
    logger.info(f"    * Loading internal mesh from: {internal_file}")
    
    mem_before = get_memory_usage_mb()
    internal_mesh = pv.read(internal_file)
    mem_after = get_memory_usage_mb()
    logger.info(f"    * Internal mesh loaded: {internal_mesh.n_cells:,} cells, {internal_mesh.n_points:,} points")
    logger.info(f"    * Memory usage: {mem_before:.1f} MB -> {mem_after:.1f} MB (+{mem_after - mem_before:.1f} MB)")
    
    # Look for surface mesh files
    surface_file = None
    # Try different naming conventions
    base_dir = os.path.dirname(internal_file)
    possible_surface_names = [
        os.path.join(base_dir, "boundary.vtk"),
        os.path.join(base_dir, "surfaces.vtk"),
        internal_file.replace("_internal.vtk", "_boundary.vtk"),
        internal_file.replace("internal.vtk", "boundary.vtk"),
    ]
    
    for sf in possible_surface_names:
        if os.path.exists(sf):
            surface_file = sf
            break
    
    if surface_file:
        logger.info(f"    * Loading surface mesh from: {surface_file}")
        surfaces_mesh = pv.read(surface_file)
    else:
        # Extract surface from internal mesh
        logger.info(f"    * No surface file found, extracting from internal mesh")
        surfaces_mesh = internal_mesh.extract_surface()
    
    logger.info(f"    * Surface mesh: {surfaces_mesh.n_cells:,} cells")
    
    return internal_mesh, surfaces_mesh


def load_foam_results(sim_path: str):
    """
    Load OpenFOAM results efficiently.
    
    Strategy:
    1. First try pre-generated VTK files (memory-efficient)
    2. Fall back to reading .foam file directly (memory-intensive)

    Returns:
        tuple: (internal_mesh, surfaces_mesh)
    """
    logger = logging.getLogger(__name__)
    
    logger.info(f"    * Loading results from: {sim_path}")
    logger.info(f"    * Initial memory usage: {get_memory_usage_mb():.1f} MB")
    logger.info(f"    * sim_path contents: {os.listdir(sim_path)[:20]}...")
    
    # Log encoding info for debugging
    import sys
    import locale
    logger.info(f"    * ENCODING CHECK in load_foam_results:")
    logger.info(f"      - sys.getdefaultencoding(): {sys.getdefaultencoding()}")
    logger.info(f"      - locale.getpreferredencoding(): {locale.getpreferredencoding(False)}")
    
    # Strategy 1: Try pre-generated VTK files (memory-efficient)
    logger.info(f"    * Attempting to load from pre-generated VTK files...")
    try:
        result = load_from_vtk_files(sim_path, logger)
        if result is not None:
            logger.info(f"    * ✅ Successfully loaded from VTK files")
            return result
        logger.info(f"    * Pre-generated VTK files not available, falling back to FOAM reader")
    except Exception as e:
        logger.warning(f"    * VTK loading failed: {e}, falling back to FOAM reader")
    
    # Strategy 2: Fall back to FOAM reader (memory-intensive)
    foam_path = os.path.join(sim_path, "results.foam")
    
    if not os.path.exists(foam_path):
        raise FileNotFoundError(f"results.foam not found at: {foam_path}")
    
    logger.info(f"    * Loading from FOAM file: {foam_path}")
    logger.info(f"    * ⚠️ WARNING: FOAM reader uses more memory than VTK files")
    
    try:
        reader = pv.get_reader(foam_path)
        logger.info(f"    * Reader created successfully")
        
        # Check if time values exist
        if not hasattr(reader, 'time_values') or len(reader.time_values) == 0:
            logger.warning(f"    * No time values found, using default read")
            mesh = reader.read()
        else:
            logger.info(f"    * Available time values: {reader.time_values}")
            # Use last timestep
            reader.set_active_time_value(reader.time_values[-1])
            logger.info(f"    * Set active time to: {reader.time_values[-1]}")
            
            mem_before = get_memory_usage_mb()
            logger.info(f"    * Memory before read: {mem_before:.1f} MB")
            
            # Read complete mesh
            mesh = reader.read()
            
            mem_after = get_memory_usage_mb()
            logger.info(f"    * Memory after read: {mem_after:.1f} MB (+{mem_after - mem_before:.1f} MB)")
        
        logger.info(f"    * Mesh loaded successfully")

        # Handle MultiBlock mesh (multiple regions or patches)
        if isinstance(mesh, pv.MultiBlock):
            logger.info(f"    * MultiBlock detected, combining blocks")
            mesh = mesh.combine()

        # Separate internal volume from boundary surfaces
        internal_mesh = mesh.extract_cells_by_type([
            pv.CellType.HEXAHEDRON, pv.CellType.TETRA, pv.CellType.WEDGE,
            pv.CellType.PYRAMID
        ])

        surfaces_mesh = mesh.extract_surface()

        logger.info(f"    * Extraction complete - internal cells: {internal_mesh.n_cells}, surface cells: {surfaces_mesh.n_cells}")
        logger.info(f"    * Final memory usage: {get_memory_usage_mb():.1f} MB")
        
        return internal_mesh, surfaces_mesh
    
    except UnicodeDecodeError as e:
        logger.error(f"    * UNICODE DECODE ERROR:")
        logger.error(f"      - encoding: {e.encoding}")
        logger.error(f"      - reason: {e.reason}")
        logger.error(f"      - position: {e.start}-{e.end}")
        import traceback
        logger.error(f"    * Full traceback: {traceback.format_exc()}")
        raise
    except Exception as e:
        logger.error(f"    * ERROR loading results: {str(e)}")
        import traceback
        logger.error(f"    * Traceback: {traceback.format_exc()}")
        raise
